public class AuthConstants {
    
    // Access Tokens
    public static final String GOREST_ACCESS_TOKEN = '0819a762db0cfd22b9cf64c1e8f95404a169d62a4719af1e9e0b44320efbe6fc';//add to custom settting
    // Add more tokens as needed

    
    // Authorization Endpoints
    public static final String EXAMPLE_AUTH_ENDPOINT = 'https://auth.example.com/account';
    // Add more authorization endpoints as needed


    
    // Other Authorization Related Constants
    public static final String AUTH_GRANT_TYPE = 'authorization_code';
    public static final String AUTH_CLIENT_ID = 'YOUR_CLIENT_ID';
    public static final String AUTH_CLIENT_SECRET = 'YOUR_CLIENT_SECRET';
    // Add more constants as needed

    // Private constructor to prevent instantiation
    private AuthConstants() {
        // This constructor will never be called
    }

}