public class EndpointManager {
    // Define endpoints as public static final variables
    public static final String GOREST_USERS 	= 		'https://gorest.co.in/public/v2/users';// add to custom setting
    public static final String GOREST_POSTS 	= 		'https://gorest.co.in/public/v2/posts';
    public static final String GOREST_COMMENTS 	= 	'https://gorest.co.in/public/v2/comments';
    public static final String GOREST_TODOS 	= 		'https://gorest.co.in/public/v2/todos';
    
    
    // Private constructor to prevent instantiation
    private EndpointManager() {
        // This constructor will never be called
    }

}